### PR TITLE
Import all indexes including their names.

### LINKED ISSUE #4: Unique indexes are named different after the conversion
On a fresh 7.10 PG GitLab installation, the index on `users` are:

```
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "index_users_on_authentication_token" UNIQUE, btree (authentication_token)
    "index_users_on_confirmation_token" UNIQUE, btree (confirmation_token)
    "index_users_on_email" UNIQUE, btree (email)
    "index_users_on_reset_password_token" UNIQUE, btree (reset_password_token)
    "index_users_on_admin" btree (admin)
    "index_users_on_created_at_and_id" btree (created_at, id)
    "index_users_on_current_sign_in_at" btree (current_sign_in_at)
    "index_users_on_name" btree (name)
    "index_users_on_username" btree (username)
```

On a 'converted' PG they are:

```
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "users_authentication_token_key" UNIQUE CONSTRAINT, btree (authentication_token)
    "users_confirmation_token_key" UNIQUE CONSTRAINT, btree (confirmation_token)
    "users_email_key" UNIQUE CONSTRAINT, btree (email)
    "users_reset_password_token_key" UNIQUE CONSTRAINT, btree (reset_password_token)
    "index_users_on_admin" btree (admin)
    "index_users_on_created_at_and_id" btree (created_at, id)
    "index_users_on_current_sign_in_at" btree (current_sign_in_at)
    "index_users_on_name" btree (name)
    "index_users_on_username" btree (username)
```

I don't know the difference between `UNIQUE CONSTRAINT` and `UNIQUE`. The index names are definitely different.

cc @DouweM

### PR DESCRIPTION
**Pull request by DouweM**
Fixes #4.

Obviates the http://doc.gitlab.com/ce/update/mysql_to_postgresql.html#rebuild-indexes section in the docs.

cc @jacobvosmaer

### CODE REVIEW

**Comment by dosire** [comment]
@DouweM awesome! I assume you'll make sure to update the docs when this is merged

**Comment by DouweM** [comment]
@dosire That was the idea :)

**Comment by jacobvosmaer** [comment]
Awesome @DouweM . Could you paste the results of the test procedure outlined in [the other PR](https://github.com/gitlabhq/mysql-postgresql-converter/pull/3#issuecomment-100889175)?

The second step after fixing the converter would be to write a (one-time) migration in gitlabhq to rename existing different-named indexes.

**Comment by jacobvosmaer** [comment]
Created #6, #7 to eliminate the schema diff.

**Pull request merged**
