### PR TITLE
Preserve default values of boolean columns.

### LINKED ISSUE #2: Default values for boolean fields are not preserved?
https://gitlab.com/gitlab-org/gitlab-ce/issues/1520#note_1197200

@DouweM wrote:

> I think this line: https://github.com/gitlabhq/mysql-postgresql-converter/blob/gitlab/db_converter.py#L158 converts tinyint(1), which MySQL uses for boolean, to a PostgreSQL boolean field, but for some reason it also runs `ALTER TABLE \"%s\" ALTER COLUMN \"%s\" DROP DEFAULT`. Does this make sense to you? I think we need to update the converter.

### PR DESCRIPTION
**Pull request by DouweM**
Fixes #2.

cc @jacobvosmaer @dosire

### CODE REVIEW

**Comment by bbodenmiller** [comment]
Fixing the convertor is great but this is still a problem for people who already used the convertor.

**Comment by DouweM** [comment]
@bbodenmiller Right. We can write a migration to fix up these people's DBs, but that's a separate issue from fixing the converter.

**Comment by jacobvosmaer** [comment]
Looks good @DouweM ; how did you test this?

**Comment by DouweM** [comment]
I created a simple table in MySQL with BOOLEAN columns with DEFAULT TRUE and DEFAULT FALSE, ran `mysqldump`, put the resulting SQL through the converter, and then executed the converted SQL on PostgreSQL. Result is exactly as expected.

**Comment by DouweM** [comment]
BOOLEAN, FALSE and TRUE are simple aliases for tinyint(1), 0 and 1 in MySQL, so that's what ends up in the mysqldump result and what the converter should look for.

**Comment by jacobvosmaer** [comment]
Sounds good @DouweM but I think this sort of thing should also be tested on an actual GitLab database.
- configure gitlab with MySQL
- `rake gitlab:setup`
- do the full converter
- `rake db:migrate`
- make a copy of schema.rb
- change database.yml to use Postgres
- `rake gitlab:setup db:migrate`
- post the diff of the schema.rb's in these PR comments.

**Comment by DouweM** [comment]
@jacobvosmaer Will do asap.

**Comment by DouweM** [comment]
@jacobvosmaer I used this PR and #5 together, to get the best result. 

The diff between the actual PosgreSQL schema.rb, and the MySQL-to-PostgreSQL schema.rb:

``` diff
diff --git a/db/schema.rb b/db/schema.rb
index 04abf9b..9da616f 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -13,9 +13,6 @@

 ActiveRecord::Schema.define(version: 20150502064022) do

-  # These are extensions that must be enabled in order to support this database
-  enable_extension "plpgsql"
-
   create_table "application_settings", force: true do |t|
     t.integer  "default_projects_limit"
     t.boolean  "signup_enabled"
@@ -186,9 +183,9 @@ ActiveRecord::Schema.define(version: 20150502064022) do

   create_table "merge_request_diffs", force: true do |t|
     t.string   "state"
-    t.text     "st_commits"
-    t.text     "st_diffs"
-    t.integer  "merge_request_id", null: false
+    t.text     "st_commits",       limit: 2147483647
+    t.text     "st_diffs",         limit: 2147483647
+    t.integer  "merge_request_id",                    null: false
     t.datetime "created_at"
     t.datetime "updated_at"
   end
@@ -269,8 +266,8 @@ ActiveRecord::Schema.define(version: 20150502064022) do
     t.string   "line_code"
     t.string   "commit_id"
     t.integer  "noteable_id"
-    t.boolean  "system",        default: false, null: false
-    t.text     "st_diff"
+    t.boolean  "system",                           default: false, null: false
+    t.text     "st_diff",       limit: 2147483647
   end

   add_index "notes", ["author_id"], name: "index_notes_on_author_id", using: :btree
@@ -338,22 +335,22 @@ ActiveRecord::Schema.define(version: 20150502064022) do
     t.datetime "created_at"
     t.datetime "updated_at"
     t.integer  "creator_id"
-    t.boolean  "issues_enabled",         default: true,     null: false
-    t.boolean  "wall_enabled",           default: true,     null: false
-    t.boolean  "merge_requests_enabled", default: true,     null: false
-    t.boolean  "wiki_enabled",           default: true,     null: false
+    t.boolean  "issues_enabled",                    default: true,     null: false
+    t.boolean  "wall_enabled",                      default: true,     null: false
+    t.boolean  "merge_requests_enabled",            default: true,     null: false
+    t.boolean  "wiki_enabled",                      default: true,     null: false
     t.integer  "namespace_id"
-    t.string   "issues_tracker",         default: "gitlab", null: false
+    t.string   "issues_tracker",                    default: "gitlab", null: false
     t.string   "issues_tracker_id"
-    t.boolean  "snippets_enabled",       default: true,     null: false
+    t.boolean  "snippets_enabled",                  default: true,     null: false
     t.datetime "last_activity_at"
     t.string   "import_url"
-    t.integer  "visibility_level",       default: 0,        null: false
-    t.boolean  "archived",               default: false,    null: false
+    t.integer  "visibility_level",                  default: 0,        null: false
+    t.boolean  "archived",                          default: false,    null: false
     t.string   "avatar"
     t.string   "import_status"
-    t.float    "repository_size",        default: 0.0
-    t.integer  "star_count",             default: 0,        null: false
+    t.float    "repository_size",        limit: 24, default: 0.0
+    t.integer  "star_count",                        default: 0,        null: false
     t.string   "import_type"
     t.string   "import_source"
   end
@@ -395,15 +392,15 @@ ActiveRecord::Schema.define(version: 20150502064022) do

   create_table "snippets", force: true do |t|
     t.string   "title"
-    t.text     "content"
-    t.integer  "author_id",                    null: false
+    t.text     "content",          limit: 2147483647
+    t.integer  "author_id",                                       null: false
     t.integer  "project_id"
     t.datetime "created_at"
     t.datetime "updated_at"
     t.string   "file_name"
     t.datetime "expires_at"
     t.string   "type"
-    t.integer  "visibility_level", default: 0, null: false
+    t.integer  "visibility_level",                    default: 0, null: false
   end

   add_index "snippets", ["author_id"], name: "index_snippets_on_author_id", using: :btree
```

I'm not quite sure what `enable_extension "plpgsql"` means.

Otherwise, te only difference is in the `limit`s, which are explicitly set for MySQL in `db/migrate/limits_to_mysql.rb`. Do we want to somehow strip those when converting to PostgreSQL?

**Comment by jacobvosmaer** [comment]
Looks great. I think we should fix the limits and extension separately while we are looking into this now.

**Pull request merged**
